### PR TITLE
Content-type parsing

### PR DESCRIPTION
**Pull request by skol-pro**
- Created Content-Type module + factory
- Refactored resource-http-interceptor factory to use content-type checker

### CODE REVIEW

**Comment by maennchen** [comment]
Could you add the bower & npm dependency?

**Comment by skol-pro** [comment]
See my comment on https://github.com/LuvDaSun/angular-hal/issues/46

**Comment by maennchen** [comment]
Ah, sorry.

1. You can install it by adding it to the `package.json` and `bower.json`.
```bash
npm install content-type --save
bower install --save jshttp/content-type
```
2. Run those commands at the end:
```bash
npm install
npm run compile
```
3. I'll write the test for you as a gist.

**Comment by skol-pro** [comment]
Awesome ok, I already ran npm install but I was afraid that it would create useless stuff.
Whatever, will keep that in mind, thank you. I'm just wondering where that "jshttp/" comes from ?

Thank you for the test, will take a look then.

**Comment by maennchen** [comment]
The `jshttp` comes from the github username of the author. I'm however afraid, that the package is in fact not compatible with bower.
I'll create a fork which will support it.

**Comment by skol-pro** [comment]
Ooooh ok I see.
By the way, I'm just discovering `npm run compile`, this is awesome ! Beginning to understand processes.

**Comment by skol-pro** [comment]
Ok I added dependencies etc. No need for new pull-request ?

**Comment by maennchen** [comment]
If you push again, the pull request will get updated.

**Comment by skol-pro** [comment]
Ok, already pushed, good.

**Comment by maennchen** [comment]
This is the test I wrote:
https://github.com/LuvDaSun/angular-hal/blob/master/test/content-type.spec.js

I had to improve a few things which you see in the latest commit.

Thank you very much.

**Comment by skol-pro** [comment]
Cool, all of this makes sense !
I guess you just forgot to `return self;` at https://github.com/LuvDaSun/angular-hal/commit/1f6ec9b437ae771a87db66b60ea383d592ba1bb5#diff-2963df74eb8dde1731c4892061716901L957 :p

**Comment by maennchen** [comment]
When angular creates a service, it does it using 'new service()' which will create an instance.
The doesn't have to be returned that way. (but does no harm either...)

**Comment by maennchen** [comment]
BTW: I just made an improvement to the README.

**Comment by skol-pro** [comment]
Oh really, thought returning `self` (or `this`) was necessary.
Perfect regarding the README, nothing can fail anymore !

**Comment by maennchen** [comment]
'''js
function withReturn() { return this;}
function without() {}
withReturn() // withReturn {}
new withReturn() // withReturn {}
without() // undefined
new without() // without {}
'''

**Comment by maennchen** [comment]
i can't write back ticks with a cell phone -.-

**Comment by skol-pro** [comment]
Ah ah :D Ok ok, not sure I got that but that's ok, will keep in mind too.

**Comment by skol-pro** [comment]
You should had the content-type dependency in the README too.
Don't know if user can choose to add the `content-type.js` stuff or has to do a `npm install`...

**Comment by skol-pro** [comment]
I mean, for those like who haven't installed angular-hal using npm at least.

**Comment by maennchen** [comment]
I opened an issue. I'll do it tomorrow.

**Comment by skol-pro** [comment]
Hehe, have a good-night ;-)

**Pull request merged**
