### PR TITLE
Add shortcuts methods for request on self

### PR DESCRIPTION
**Pull request by agouriou**
As discussed in #61 this add shortcuts methods for call on self.

This enable more fluent calls like:
`resource.$putSelf(payload)`

instead of
`resource.$put(null, null, payload)` or `resource.$put($halConfiguration.self, null, payload)`

### CODE REVIEW

**Comment by maennchen** [comment]
Could you also write a very simple test for that functionality?

**Comment by agouriou** [comment]
Sure, I'll do that soon.

**Comment by maennchen** [comment]
Thank you very much.

**Comment by agouriou** [comment]
You're welcome, thanks for this lib.

**Pull request merged**
